### ISSUE TITLE
call a function that doesn't exist

### ISSUE THREAD

**Issue by Hyper-XDK** [Ruk33/vrJASS#29]
When compiling the script, any trigger that doesn't have a InitTrig_TrgName function cause errors and prevent map from start!

I've used MPQEditors to see what code looks like after compling by JassHelpers.
Vexorian's has generated:
`//Function not found: call InitTrig_natives()`

But your one's has generated:
`call InitTrig_natives(  )`

For instance you can download [this map](http://www.hiveworkshop.com/attachments/extract-play-zip.131058/) Try "SharpCraft - Natives.w3x" file.
and you just need to open the map in editor and save it while vrJASS is activated;
the map doesn't seem to be work after that.

**Comment by Ruk33** [comment]
Hi MasterHK, I'm gonna be checking, thanks for reporting.

**Comment by MasterHK** [comment]
I "Love" your plugin more than any other JassHelper,
fix it asap please... :)

**Comment by Ruk33** [comment]
Hi MasterHK, I've tried the map with only the 'natives' trigger enabled and it worked.

Are you using the last version of vrJASS?, what triggers do you have enabled?, what version of JNGP are you using?, did it generated/opened any log file?

**Comment by Hyper-XDK** [comment]
> Are you using the last version of vrJASS?

Yes, [v1.9](https://github.com/Ruk33/vrJASS/releases/tag/v1.9.0)

> what triggers do you have enabled?

No more, I'd just press the "Save button"

> what version of JNGP are you using?

[v2.0.9](http://s000.tinyupload.com/index.php?file_id=38527207818089958991), from the [main thread](http://blizzardmodding.info/4263/the-jass-newgen-pack-jngp-2-0/).

> did it generated/opened any log file?

No. This is my actual Problem!

However, this is my [wehack.lua](https://uploadfiles.io/a5f26) if you want to take a look...

**Comment by Ruk33** [comment]
Ok, checking. Meanwhile, could you please paste here the generated code (war3map.j).

**Comment by Hyper-XDK** [comment]
sure, [here](https://uploadfiles.io/1ca5656).

**Comment by Ruk33** [comment]
MasterHK I tried with your wehack.lua but it gives many errors when saving the map. Please try with a clean installation of JNGP (it worked for me).

The result of the compiler is:

```
132:40 Syntax error no viable alternative at input 'nativeHttpRequesttakesstringmethod'

native StringPos       takes string str, string sub returns integer
native StringReverse   takes string str returns string
native StringTrim      takes string str returns string
native StringTrimStart takes string str returns string
native StringTrimEnd   takes string str returns string
native StringSplit     takes string str, string sub, integer index returns string
native StringInsert    takes string str, integer index, string val returns string

// HTTP
native HttpRequest         takes string method, string url, string cookies, string values returns string
----------------------------------------^
native HttpLastCookie      takes nothing returns string
native HttpPendingResponse takes integer id returns string
native StartRequest        takes string method, string url, string cookies, string values, integer id returns nothing

// Thread
//native NewThread takes code func returns nothing//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_natives(  )
endfunction
```

(method is a keyword)

**Comment by Hyper-XDK** [comment]
But `InitTrig_natives()` is an undefined method!

> I tried with your wehack.lua but it gives many errors when saving the map.

This is a big problem because I don't get any error...

However I want to check something about that and I will post the result here.

**Comment by Ruk33** [comment]
Don't worry about it. The compiler takes care and will remove it if necessary ^^

**Comment by Hyper-XDK** [comment]
I promise we won't be able to find out how it can be done!

![2016_9_18_20_41_43](https://cloud.githubusercontent.com/assets/8487749/18618992/cfd7aa00-7e06-11e6-8163-067151c5ef6c.jpg)

![2016_9_18_20_45_10](https://cloud.githubusercontent.com/assets/8487749/18618993/cfdebc0a-7e06-11e6-83e1-e15d5d420d54.jpg)

check these [map files](https://uploadfiles.io/20252) please.

**Comment by Ruk33** [comment]
Ok, remember that I'm only testing the 'natives' trigger (since the other have features that are yet not supported by vrJASS, for example `readonly`)

![image](https://cloud.githubusercontent.com/assets/1719111/18619076/92058fc2-7dc9-11e6-97be-28e67ce577b8.png)

![image](https://cloud.githubusercontent.com/assets/1719111/18619089/ac044a8a-7dc9-11e6-8a15-fa187f24b79d.png)

Are you sure that vrJASS is actually running?. To try it, please disable all triggers, create a new one and paste this:

```
library Test
    function onInit
        call BJDebugMsg(1)
    end
end
```

It should throw you an error (or at least create a log file):

```
105:13 Element <msg> must have/return a value of type <string> but given <integer>
```

**Comment by Hyper-XDK** [comment]
Saved without any error throw!

Give me your wehack.lua please.

**Comment by Ruk33** [comment]
It is the one that the JNGP came with: 
[wehack.zip](https://github.com/Ruk33/vrJASS/files/478991/wehack.zip)

**Comment by Hyper-XDK** [comment]
Could you please explain this for me?
`blizzmod\\MTT.exe --vrjass=`

( and I have to say map saved without error when compiling again... :/ )

**Comment by Ruk33** [comment]
I was also looking at that, but its something from moyack so I couldn't tell :\.

**Comment by Hyper-XDK** [comment]
I mean, is it correct?

**Comment by Hyper-XDK** [comment]
Now I want to ask you... :)

> what version of JNGP are you using?

**Comment by Ruk33** [comment]
> I mean, is it correct?

I got the same thing (and its working) so yes ^^

> what version of JNGP are you using?

Same as you, v2.0.9 from the main thread.

**Comment by Hyper-XDK** [comment]
> what version of JNGP are you using?
> Same as you, v2.0.9 from the main thread.

Are you sure? :|

`grim.exists("jasshelper\\ruke\\vrjassc-jar-with-dependencies.jar")`

**Comment by Ruk33** [comment]
Yep, I just downloaded and tested everything with that version (I also got that line on my wehack.lua).

**Comment by Hyper-XDK** [comment]
I have downloaded this version:
jngp_209.7z
5.94 MB (6,234,622 bytes)

and this is my archive content:
![jngp_209](https://cloud.githubusercontent.com/assets/8487749/18619289/bb7f1faa-7e0d-11e6-8bdc-84939ebdf6b8.jpg)

After rename the jass helper folder and move vrjassc... to jasshelper\ruke directory from vrJASS directory
JassHelper appeared but still I have this error when I press the Save button 
![err](https://cloud.githubusercontent.com/assets/8487749/18619305/494558e0-7e0e-11e6-873c-fce398b3bc5a.jpg)

It's pretty clear that blizzmod\MTT doesn't meet vrjass yet and so he doesn't like him...

Nevermind, Link me to your JNGP please... :)

**Comment by Ruk33** [comment]
Apparently moyack already included vrJASS in this version so you don't have to do anything (just unzip and you're ready to go).

**Comment by Hyper-XDK** [comment]
Now When I save map and vrJASS activated, this is what I get:

![safe](https://cloud.githubusercontent.com/assets/8487749/18619441/a11a8128-7e11-11e6-8e56-01958bc6584b.jpg)

Can I use this command instead?
`toolresult = wehack.runprocess2("java -jar vrjass/vrjassc-jar-with-dependencies.jar \"" .. mappath .. "\" -log=vrjass.txt -result=\"" .. mappath .. "\"")`

**Comment by Ruk33** [comment]
Excellent, I have a similar error, did the log file showed up?

And yes, you can change the command but use this instead:
`wehack.runprocess2("java -jar jasshelper/ruke/vrjassc-jar-with-dependencies.jar jasshelper/ruke/common.j jasshelper/ruke/Blizzard.j \"" .. mappath .. "\" -log=vrjass.txt -result=\"" .. mappath .. "\"")`

**Comment by Hyper-XDK** [comment]
> did the log file showed up?

Not Yet... :/

Good News!
with `java -jar jasshelper/ruke/vrjassc-jar-with-dependencies.jar...` command everything seems to be fine now :)
vrjass got accepted `-log` with the open hugs!
and shows me my compile errors (opens vrjass.txt in notepad as you had expected).

I'm gonna be checking them and testing map and answer here soon,
But I guess it must be fixed at the meantime...

Thanks for all of your help...

**Comment by Ruk33** [comment]
Great!

You're welcome ^^, let me know if anything else happens.
